services:
  - type: web
    name: fastapi-server
    env: python
    plan: free
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: PORT
        value: 10000

  - type: web
    name: react-client
    env: node
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port 4173
    staticPublishPath: dist
